#!/bin/sh
# See LICENSE file for details
# siren is a simple script to connect to wireless networks on linux machines

# cwpa version
VERSION=0.1

################################################################################
# interfaces and flags
################################################################################

iface=wls3
WPASUPPLICANTDIR=/etc/wpa_supplicant

################################################################################
# functions
################################################################################

usage () {
    printf "Usage:\n"
    printf "%s [-h] [-l] [-v] [-c NETWORK]\n" "$0"
    printf "%s -h:    show this message\n" "$0"
    printf "%s -l:    list configured networks\n" "$0"
    printf "%s -c:    connect to one of the networks listed with the -l option\n" "$0"
    printf "%s -v:    show cwpa version\n" "$0"
}

show_version () {
    printf "$0-%s\n" "$VERSION"
}

connect_to_network () {
    printf "connecting to %s ...checking permissions\n" "$NETWORK"
    wpa_supplicant -B -i wls3 -c/etc/wpa_supplicant/"$NETWORK".conf
}

search_for_network () {
    printf "You must be root to use iw's scan feature:\n"
    iw dev "$iface" scan | less
}

list_configured_networks () {
    ls -1 $WPASUPPLICANTDIR/*.conf
}

################################################################################
# argument parsing
################################################################################

while :
do
    case $1 in
	-h)
	    usage
	    exit 0
	    ;;
	-s)
	    search_for_network
	    exit 0
	    ;;
	-l)
	    list_configured_networks
	    exit 0
#	    break
	    ;;
	-c)
	    NETWORK=$2
	    connect_to_network
	    exit 0
	    ;;
	-v)
	    show_version
	    exit 0
	    ;;
	*)
	    usage
	    exit 1
	    ;;
    esac
done

