#!/bin/sh
# See LICENSE file for details
# siren is a simple script to connect to wireless networks on linux machines

# cwpa version
VERSION=0.1

################################################################################
# interfaces and flags
################################################################################

iface=wls3
WPASUPPLICANTDIR=/etc/wpa_supplicant/

################################################################################
# functions
################################################################################

usage () {
    printf "$0 -h:    show this message\n"
    printf "$0 -l:    list configured networks\n"
    printf "$0 -c:    connect to one of the networks listed with the -l option\n"
}


connect_to_network () {
    network=$2
    printf "connecting to network %s...checking permissions\n" $network
#    sudo wpa_supplicant -B -i wls3 -c/etc/wpa_supplicant/network.conf
}

search_for_network () {
    printf "You must be root to use iw's scan feature:\n"
    sudo iw dev "$iface" scan | less
}

list_configured_networks () {
    ls -1 $WPASUPPLICANTDIR/*.conf
#    exit 0
}

################################################################################
# argument parsing
################################################################################

while :
do
    case $1 in
	-h)
	    usage
	    exit 0
	    ;;
	-s)
	    search_for_network
	    exit 0
	    ;;
	-l)
	    list_configured_networks
	    exit 0
#	    break
	    ;;
	*)
	    usage
	    exit 1
	    ;;
    esac
done

